#!/bin/bash

# Escanea las redes Wi-Fi disponibles y extrae los SSIDs y la seguridad
networks=$(nmcli -t -f SSID,SECURITY device wifi list | awk -F: '!seen[$1]++ {print $1 ":" $2}')

# Muestra el menú con rofi y guarda la selección
selected_network=$(echo "$networks" | awk -F: '{print $1}' | rofi -dmenu -p "Seleccionar red Wi-Fi")

# Si el usuario selecciona una red
if [ -n "$selected_network" ]; then
    # Obtiene la seguridad de la red seleccionada
    security=$(echo "$networks" | grep "^$selected_network" | awk -F: '{print $2}')
    
    # Si la red tiene seguridad (no es una red abierta)
    if [ "$security" != "--" ]; then
        # Pregunta la contraseña
        wifi_password=$(rofi -dmenu -p "Contraseña para $selected_network")

        # Conectar a la red seleccionada con contraseña
        if [ -n "$wifi_password" ]; then
            nmcli device wifi connect "$selected_network" password "$wifi_password"
        else
            echo "Contraseña vacía, no se pudo conectar."
        fi
    else
        # Conectar a la red abierta
        nmcli device wifi connect "$selected_network"
    fi
fi
